<%@ Page Title="" Language="C#" MasterPageFile="~/Adminmasterpage.master" AutoEventWireup="true" CodeFile="AddVenue.aspx.cs" Inherits="AddVenue" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
    <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="Eventcode" DataSourceID="SqlDataSource1" GridLines="Horizontal" ShowHeaderWhenEmpty="True">
    <AlternatingRowStyle BackColor="#F7F7F7" />
    <Columns>
        <asp:BoundField DataField="Eventcode" HeaderText="Eventcode" InsertVisible="False" ReadOnly="True" SortExpression="Eventcode" />
        <asp:BoundField DataField="Event_type" HeaderText="Event_type" SortExpression="Event_type" />
    </Columns>
    <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
    <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
    <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
    <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
    <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
    <SortedAscendingCellStyle BackColor="#F4F4FD" />
    <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
    <SortedDescendingCellStyle BackColor="#D8D8F0" />
    <SortedDescendingHeaderStyle BackColor="#3E3277" />
</asp:GridView>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:OkasionDbConnectionString %>" SelectCommand="SELECT * FROM [event]" UpdateCommand="update [event] set [Event_type]=@Event_type where [eventcode]=@eventcode" DeleteCommand="Delete from [event] where [eventcode]=@eventcode"></asp:SqlDataSource>
    
</asp:Content>

